# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 11671 - FCDS
tagline: FCDS
description: The official course page for 11671 FCDS at CMU
author: Master of Computational Data Science at Carnegie Mellon University
baseurl: '/11671' # the subpath of your site, e.g. /blog
url: 'https://mcds-cmu.github.io' # the base hostname & protocol for your site, e.g. http://example.com
exclude: ["Gemfile", "Gemfile.lock", "LICENSE", "vendor"]
logo: "/assets/images/CMU_MCDS_logo_Parent_Horizontal_Full-Color_PMS1024_1.png"

# Theme settings
remote_theme: just-the-docs/just-the-docs@v0.3.3
color_scheme: mcds
search_enabled: true
heading_anchors: true
permalink: pretty
aux_links:
  # Kevin Lin:
  #   - 'https://kevinl.info'
  # Just the Class on GitHub:
  #   - 'https://github.com/kevinlin1/just-the-class'
footer_content:

# Collections for website data
collections:
  staffers:
  modules:
  schedules:
  announcements:
# Default layouts for each collection type
defaults:
  - scope:
      path: ''
      type: staffers
    values:
      layout: staffer
      subpath: '/assets/images/'
  - scope:
      path: ''
      type: modules
    values:
      layout: module
  - scope:
      path: ''
      type: schedules
    values:
      layout: schedule
  - scope:
      path: ''
      type: announcements
    values:
      layout: announcement

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

ga_tracking: UA-234353414-1

plugins:
  - jekyll-seo-tag
